name: Update Snap dependencies

on:
  schedule:
    - cron: "9 7 * * *"
  workflow_dispatch:

concurrency:
  group: update-snap-dependencies
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  update-snap:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Update Snapcraft dependencies
        uses: ubuntu/desktop-snaps@f1886f483e2251bc0a1d099951946966677ffbd4 # stable
        with:
          token: ${{ github.token }}
          repo: ${{ github.repository }}
          version-schema: '^ghostpdl-(\d+\.\d+\.\d+)'
